<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('styles/css/style.css'))
            ->prependStylesheet($this->basePath('bower_components/bootstrap/dist/css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->appendFile($this->basePath('bower_components/jquery/dist/jquery.min.js'))
            ->appendFile($this->basePath('bower_components/angular/angular.min.js'))
            ->appendFile($this->basePath('js/main.js'))
            
        ?>
    </head>
    <body data-auth="<?php echo (!empty($this->identity) ? "loggedIn" : ""); ?>">
        <header>
            <nav class="menu-bar" role="navigation">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-9">
                            <ul class="main-menu">
                                <li class=""><a href="<?= $this->url('home') ?>">Home</a></li>
                            </ul>
                        </div>
                        <div class="col-xs-3">
                            <ul class="auth-menu">
                                <li class="<?php echo (!empty($this->identity) ? "hide" : ""); ?>"><a href="<?= $this->url('auth') ?>">LogIn</a></li>
                                <li class="<?php echo (!empty($this->identity) ? "" : "hide"); ?>"><a href="<?= $this->url('auth/logout') ?>">LogOut</a></li>
                            </ul>
                        </div>
                        
                    </div>
                </div>
            </nav>
        </header>
        
        
        <main>
            <div class="container">
                <?= $this->content ?>
            </div>
        </main>
        
        
        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
                    </div>
                </div>
            </div>
        </footer>
        <?= $this->inlineScript() ?>
    </body>
</html>
